---
- hosts: localhost
  tasks:
    - name: Uninstall Jenkins
      kubernetes.core.helm:
        name: jenkins
        release_namespace: jenkins
        state: absent

    - name: Delete Jenkins namespace
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: jenkins
